### ISSUE TITLE
How otoclone operates

### ISSUE THREAD

**Issue by djmattyg007** [bilyes/otoclone#1]
Does this tool actually make backups, or does it just perform automatic synchronisation to remote storage whenever something changes?

To illustrate the difference, what would happen in the situation where something came along and truncated all of the files in the source directory so they were all completely empty zero-byte files? If the changes would be blindly copied across to the remote storage with no way of recovering the previous versions, then you haven't created a backup.

**Comment by bilyes** [comment]
Hey @djmattyg007, Thanks for your interest in otoclone.

Currently there are 2 backup strategies supported:
- `sync` makes the destination match the source. Meaning that if files get removed from the source they will be removed from the destination as well.
- `copy` creates new files in the destination and updates existing ones. This does not remove files from the destination even if they're missing in the source at the time of the backup.

As for versioning, it is not supported yet but it's a great feature to have.

Does this answer your questions?

**Comment by djmattyg007** [comment]
Yes, it does. I recommend updating your readme to make it clear that this isn't actually a backup tool. An actual backup tool would let you recover data in the event your files are tampered with unexpectedly.

**Comment by bilyes** [comment]
Thanks for the suggestion.
